[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
#sauron = { path = "../../", features = ["log-patches"] }
sauron = "0.70.0"
log = "0.4"
console_log = "0.2"
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
