[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[lib]
name = "frontend"
path = "src/main.rs"
crate-type = ["cdylib"]

[dependencies]
sauron = "0.70.0"
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
hyper="0.14"
tokio = { version = "1", features = ["full"] }
