name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main", "develop", "be-develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-mathnet-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build backend
      run: |
        cd mathnet-server
        cargo build --verbose
    - name: Run mathnet-server tests
      run: |
        cd mathnet-server
        cargo test --verbose

  # build-client:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Build client
  #     run: |
  #       cd client
  #       cargo build --verbose
  #   - name: Run client tests
  #     run: |
  #       cd client
  #       cargo test --verbose